name: Build

on:
    push:
        branches: [main, feature/GUUI-3560-design-refresh]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout latest code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set up NodeJS v22
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build
              
            - name: Create tarball of dist
              run: tar -czf giovanni.tar.gz dist

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: giovanni-tarball
                  path: giovanni.tar.gz
                  overwrite: true